-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgfRfLA7hk/r7EpK2e
gR+5cKSK56JGAIFk4BkWLFZb3u2gCgYIKoZIzj0DAQehRANCAATLMi4zPz4lxJ2Y
XlbD6ObmzcPfqETDY4oEiblv2pDbus+T3eCn1yCVTBSBKRfbYGLZmPRrCGuku814
JIHmjVPM
-----END PRIVATE KEY-----