name: base_bloc
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter_dotenv: ^5.0.0
  flutter_svg: any
  pull_to_refresh: ^2.0.0
  logger: ^1.0.0
  event_bus: ^2.0.0
  get_storage: ^2.1.1
#  get_storage: ^2.0.2  # save data to storage(sharePref)
  intl: any
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.9
  flutter_bloc: ^8.1.1
  device_info: any
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^2.15.1
  connectivity_plus: ^2.3.0 #internet connection
  diacritic: ^0.1.3
  back_button_interceptor: ^6.0.1
  equatable: ^2.0.5
  dio: ^4.0.6
  fluro: ^2.0.3
  visibility_detector: any
  easy_localization: ^3.0.1
  flutter_facebook_auth: any
  crypto: ^3.0.1
  html: ^0.15.4
  url_launcher: any
  permission_handler: ^11.0.0
  extended_image: ^8.1.0
  rxdart: ^0.27.7
  focus_detector: any
  firebase_remote_config: ^4.3.8
  package_info_plus: 4.2.0
  dropdown_button2: ^2.3.9
  scroll_to_index: ^3.0.1
  google_sign_in: any
  firebase_auth: any


dev_dependencies:
  flutter_facebook_keyhash: ^0.0.4
  change_app_package_name: ^1.1.0
  flutter_gen: ^5.2.0
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/ca/
    - assets/png/
    - assets/icon/
    - assets/translations/
    - assets/json/
    - assets/font/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/Inter-Black.ttf
        - asset: assets/font/Inter-Bold.ttf
        - asset: assets/font/Inter-ExtraBold.ttf
        - asset: assets/font/Inter-ExtraLight.ttf
        - asset: assets/font/Inter-Light.ttf
        - asset: assets/font/Inter-Medium.ttf
        - asset: assets/font/Inter-Regular.ttf
        - asset: assets/font/Inter-Thin.ttf
        - asset: assets/font/Inter-SemiBold.ttf
          style: normal

  # fonts:
  #   - family: Schyler   
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
